### PR TITLE
Max job name length

### LINKED ISSUE #23: Handle long gordo job name errors
I doofed with long gordo name again and made `main` panic.  Just archiving this here for now.

> ApiError Invalid ("Job.batch \"gordo-deploy-job-threading-test-worker2-connections-50-batch10-1\" is invalid: spec.template.labels: Invalid value: \"gordo-deploy-job-threading-test-worker2-connections-50-batch10-1\": must be no more than 63 characters") }
thread 'main' panicked at 'not yet implemented: Haven't implemented a way to deal with this, exiting.', src/main.rs:267:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

### PR DESCRIPTION
**Pull request by milesgranger**
Will close #23 

- Change prefix of deploy job from `gordo-deploy-job` to `gordo-dpl`
- Ensure the generated name is at most 63 chars.

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -198,11 +198,16 @@ fn start_gordo_deploy_job(
...
-        "gordo-deploy-job-{}-{}",
+    let mut job_name = format!(
+        "gordo-dpl-{}-{}",
         &gordo.metadata.name,
         &gordo.metadata.generation.map(|v| v as u32).unwrap_or(0)
     );
+    // Max length of name can only be 63 char in length, favoring the tail end of the name
+    if job_name.len() > 63 {
+        let len = job_name.len();
+        job_name = job_name[(len - 63)..len].to_owned();
```
Comment (epa095) [inline src/main.rs]: What about rather taking the last 52 chars, and then prepending `gordo-dpl-` to it? Then at least we will always have that in the front?

File: src/main.rs [hunk 2]
```diff
@@ -198,11 +198,16 @@ fn start_gordo_deploy_job(
     let gordo_config = serde_json::to_string(&gordo.spec.config).unwrap();
 
     // Create the job.
-    let job_name = format!(
-        "gordo-deploy-job-{}-{}",
+    let mut job_name = format!(
+        "gordo-dpl-{}-{}",
```
Comment (epa095) [inline src/main.rs]: :+1:

**Review by epa095 — APPROVED** [review]
LGTM
